USE learn8;
GO

CREATE TABLE Company (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(20) NOT NULL,
    AddressId INT NOT NULL,
    CONSTRAINT FK_Company_Address FOREIGN KEY (AddressId) REFERENCES Address(Id)
);
GO